-- 1. 사용자 관리
CREATE TABLE TB_USER (
    USER_ID VARCHAR(20) PRIMARY KEY,
    USER_NM VARCHAR(50) NOT NULL,
    USER_PWD VARCHAR(100) NOT NULL,
    DEPT_NM VARCHAR(50),
    JOB_ROLE VARCHAR(30),
    POSITION_NM VARCHAR(30),
    CAREER_YEARS INT DEFAULT 0,
    JOB_FIELD VARCHAR(50),
    CURRENT_LOAD DECIMAL(5,2) DEFAULT 0.00,
    JOIN_DT DATE,
    AUTH_LEVEL INT DEFAULT 2,
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. 고객 관리
CREATE TABLE TB_CUSTOMER (
    CUST_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUST_NM VARCHAR(100) NOT NULL,
    BIZ_REG_NO VARCHAR(20),
    CEO_NM VARCHAR(50),
    PIC_NM VARCHAR(50),
    PIC_TEL VARCHAR(20),
    PIC_EMAIL VARCHAR(100),
    CUST_ADDR VARCHAR(255),
    CUST_REMARK TEXT
);

-- 3. 영업 관리
CREATE TABLE TB_SALES (
    SALES_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUST_ID INT,
    SALES_USER_ID VARCHAR(20),
    SALES_TITLE VARCHAR(200),
    EXPECTED_AMT BIGINT,
    EXPECTED_DT DATE,
    PROBABILITY INT,
    STATUS VARCHAR(20),
    SALES_CONTENT TEXT,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUST_ID) REFERENCES TB_CUSTOMER(CUST_ID),
    FOREIGN KEY (SALES_USER_ID) REFERENCES TB_USER(USER_ID)
);

-- 4. 계약 관리
CREATE TABLE TB_CONTRACT (
    CONT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SALES_ID INT,
    CONT_NM VARCHAR(200),
    CONT_AMT BIGINT,
    START_DT DATE,
    END_DT DATE,
    CONT_DT DATE,
    PIC_USER_ID VARCHAR(20),
    CONT_STATUS VARCHAR(20),
    CONT_REMARK TEXT,
    FOREIGN KEY (SALES_ID) REFERENCES TB_SALES(SALES_ID),
    FOREIGN KEY (PIC_USER_ID) REFERENCES TB_USER(USER_ID)
);

-- 5. 프로젝트 관리
CREATE TABLE TB_PROJECT (
    PROJ_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONT_ID INT,
    PROJ_NM VARCHAR(200),
    PROJ_TYPE VARCHAR(50),
    STATUS VARCHAR(20),
    MAIN_MGR_ID VARCHAR(20),
    SUB_MGR_ID VARCHAR(20),
    START_DT DATE,
    END_DT DATE,
    PROGRESS_RATE DECIMAL(5,2) DEFAULT 0.00,
    COMPLEXITY_SCORE INT,
    FOREIGN KEY (CONT_ID) REFERENCES TB_CONTRACT(CONT_ID),
    FOREIGN KEY (MAIN_MGR_ID) REFERENCES TB_USER(USER_ID),
    FOREIGN KEY (SUB_MGR_ID) REFERENCES TB_USER(USER_ID)
);

-- 6. 세부 달성 항목
CREATE TABLE TB_PROJECT_TASK (
    TASK_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJ_ID INT,
    TASK_NM VARCHAR(200),
    TASK_CONTENT TEXT,
    MANAGER_ID VARCHAR(20),
    WEIGHT INT,
    IS_DONE CHAR(1) DEFAULT 'N',
    START_DT DATE,
    END_DT DATE,
    DONE_DT DATETIME,
    FOREIGN KEY (PROJ_ID) REFERENCES TB_PROJECT(PROJ_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES TB_USER(USER_ID)
);

-- 7. 청구 및 정산
CREATE TABLE TB_BILLING (
    BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJ_ID INT,
    BILL_TITLE VARCHAR(200),
    BILL_AMT BIGINT,
    TAX_BILL_DT DATE,
    PAY_DT DATE,
    IS_PAID CHAR(1) DEFAULT 'N',
    ACTUAL_PAY_DT DATE,
    BILL_REMARK TEXT,
    FOREIGN KEY (PROJ_ID) REFERENCES TB_PROJECT(PROJ_ID)
);

-- 8. AI 분석 로그
CREATE TABLE TB_AI_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    REF_ID INT,
    AI_CATEGORY VARCHAR(50),
    INPUT_DATA TEXT,
    RESULT_DATA TEXT,
    REASONING TEXT,
    CONFIDENCE DECIMAL(5,2),
    CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 9. 공통 첨부파일
CREATE TABLE TB_ATTACHMENT (
    FILE_ID INT AUTO_INCREMENT PRIMARY KEY,
    REF_TYPE VARCHAR(20),
    REF_ID INT,
    ORG_FILE_NM VARCHAR(255),
    SAVE_FILE_NM VARCHAR(255),
    FILE_PATH VARCHAR(500),
    FILE_SIZE BIGINT,
    FILE_EXT VARCHAR(10),
    DOWNLOAD_CNT INT DEFAULT 0,
    REG_USER_ID VARCHAR(20),
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REG_USER_ID) REFERENCES TB_USER(USER_ID)
);pms_dbpms_dbpms_dbpms_db